"""initial_migration

Revision ID: 9956ece44f8b
Revises: 
Create Date: 2026-02-25 21:14:47.799664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9956ece44f8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'blocked', name='walletstatus', native_enum=False), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', 'CNY', name='currency', native_enum=False), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=11, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.CheckConstraint("currency in ('USD', 'EUR', 'RUB', 'CNY')", name='ck_wallets_currency'),
    sa.CheckConstraint("status in ('active', 'inactive', 'blocked')", name='ck_wallets_status'),
    sa.CheckConstraint('balance >= 0', name='ck_wallets_balance_non_negative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_wallet_id', sa.Integer(), nullable=False),
    sa.Column('receiver_wallet_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_process', 'completed', 'failed', 'blocked', name='transactionstatus', native_enum=False), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', 'CNY', name='currency', native_enum=False), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=11, scale=2), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.CheckConstraint("currency in ('USD', 'EUR', 'RUB', 'CNY')", name='ck_transactions_currency'),
    sa.CheckConstraint("status in ('in_process', 'completed', 'failed', 'blocked')", name='ck_transactions_status'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['receiver_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['sender_wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('wallets')
    op.drop_table('users')
    # ### end Alembic commands ###
