"""add-users-table-check-status-constraint

Revision ID: c01f0af0586d
Revises: d531a78ebe3b
Create Date: 2026-02-28 11:23:28.297348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01f0af0586d'
down_revision: Union[str, Sequence[str], None] = 'd531a78ebe3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
