"""initial_migration

Revision ID: d531a78ebe3b
Revises: 9956ece44f8b
Create Date: 2026-02-28 11:12:46.326292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd531a78ebe3b'
down_revision: Union[str, Sequence[str], None] = '9956ece44f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('active', 'inactive', 'blocked', name='userstatus', native_enum=False), nullable=False))
    op.drop_constraint(op.f('wallets_owner_id_fkey'), 'wallets', type_='foreignkey')
    op.create_foreign_key(None, 'wallets', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.create_foreign_key(op.f('wallets_owner_id_fkey'), 'wallets', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
