"""changes for top-up and withdrawal

Revision ID: dd2a063e1d9f
Revises: c01f0af0586d
Create Date: 2026-09-21 13:38:49.221560

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd2a063e1d9f"
down_revision: str | Sequence[str] | None = "c01f0af0586d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "type",
            sa.Enum(
                "top_up",
                "transfer",
                "withdrawal",
                name="transactiontype",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.execute("UPDATE transactions SET type = 'transfer'")
    op.alter_column("transactions", "type", nullable=False)
    op.alter_column(
        "transactions", "sender_wallet_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "transactions", "receiver_wallet_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_check_constraint(
        "ck_transactions_type",
        "transactions",
        "type in ('top_up', 'transfer', 'withdrawal')",
    )
    op.create_check_constraint(
        "ck_transactions_types_compatibility",
        "transactions",
        "(type = 'top_up' AND sender_wallet_id IS NULL AND receiver_wallet_id IS NOT NULL) OR (type = 'transfer' AND sender_wallet_id IS NOT NULL AND receiver_wallet_id IS NOT NULL) OR (type = 'withdrawal' AND receiver_wallet_id IS NULL AND sender_wallet_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions", "receiver_wallet_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "transactions", "sender_wallet_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("transactions", "type")
    # ### end Alembic commands ###
